#!/usr/bin/env bash
set -euo pipefail

echo "Install operator-sdk"

ARCH=$(case $(arch) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(arch) ;; esac)
OS=$(uname | awk '{print tolower($0)}')

OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/latest/download
curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}

chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

echo "Install OPM tooling"
OPM_VERSION=v1.31.0
OPM_DL_URL=https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm

curl -LO ${OPM_DL_URL}
chmod +x linux-amd64-opm && sudo mv linux-amd64-opm /usr/local/bin/opm