#!/usr/bin/env bash
set -euo pipefail

echo "Deactivate global git-lfs settings"
git config --system 'fedora.git-lfs.no-modify-config' true

echo "Install packages"
dnf install -y \
adobe-source-code-pro-fonts \
make \
vim \
openssl \
openssh-askpass \
httpie \
golang \
git \
git-lfs \
bind-utils \
skopeo \
buildah \
libxshmfence \
jq \
graphviz \
java-17-openjdk.x86_64

echo "Install Task"
sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin