#!/usr/bin/env bash
set -euo pipefail

echo "Install packages"

dnf install -y \
adobe-source-code-pro-fonts \
make \
vim \
openssl \
openssh-askpass \
httpie \
golang \
git \
bind-utils \
skopeo \
buildah \
libxshmfence \
jq
