#!/usr/bin/env bash
set -e

echo "Install tekton"

# dnf copr enable -y chmouel/tektoncd-cli
# dnf install -y tektoncd-cli

rpm -Uvh https://github.com/tektoncd/cli/releases/download/v0.32.2/tektoncd-cli-0.32.2_Linux-64bit.rpm


echo "Install PAC"
rpm -Uvh https://github.com/openshift-pipelines/pipelines-as-code/releases/download/v0.21.5/tkn-pac-0.21.5_linux-x86_64.rpm