#!/usr/bin/env bash
set -e

echo "Install tekton"

# dnf copr enable -y chmouel/tektoncd-cli
# dnf install -y tektoncd-cli

rpm -Uvh https://github.com/tektoncd/cli/releases/download/v0.30.1/tektoncd-cli-0.30.1_Linux-64bit.rpm
