name: toolbox-cso-t4c-dev-release
on:
  push:
    branches:
      - main
    paths:
      - 'cso-t4c-dev/**'
env:
  IMAGE_NAME: toolbox-cso-t4c-dev
  TAG: latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: echo ::set-output name=tag::${{ env.TAG }}
      - name: Get timestamp
        id: timestamp
        run: echo ::set-output name=timestamp::$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - name: Build image
        id: build-with-buildah
        uses: redhat-actions/buildah-build@v1
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.tag.outputs.tag }}
          context: ./cso-t4c-dev
          dockerfiles: |
            ./cso-t4c-dev/Dockerfile
          build-args: |
            BUILD_DATE=${{ steps.timestamp.outputs.timestamp }}
            IMAGE_VERSION=${{ steps.tag.outputs.tag }}
      - name: Push to Github
        id: push-to-github
        uses: redhat-actions/push-to-registry@v1
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ steps.tag.outputs.tag }}
          registry: ${{ secrets.GHCR_REPO }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

